import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import localFont from "next/font/local";
import MobileMenu from "./-component/MobileMenu";

const vazirFont = localFont({
  src: "../public/font/Vazirmatn-Regular.woff2",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vazirFont.className}>
        {children} <MobileMenu />
      </body>
    </html>
  );
}
